name: NerdSpawn
main: nu.nerd.nerdspawn.NerdSpawn
version: ${project.version}
description: ${project.description}
website: ${project.url}
author: Travis Watkins

commands:
  spawn:
    description: Teleports you to the spawn location
    permission: nerdspawn.spawn
    usage: |
           Incorrect usage of /<command>. Examples:
           /<command> - Teleport to spawn
           /<command> reload - Reloads configuration
  setspawn:
    description: Sets the spawn location
    permission: nerdspawn.setspawn
    usage: |
           Incorrect usage of /<command>. Examples:
           /<command> - Sets spawn location
  setfirstspawn:
    description: Sets the initial spawn location
    permission: nerdspawn.setfirstspawn
    usage: |
           Incorrect usage of /<command>. Examples:
           /<command> - Sets initial spawn location

permissions:
  nerdspawn:
    description: Allow a player all spawn permissions
    children:
      nerdspawn.spawn: true
      nerdspawn.setspawn: true
      nerdspawn.setfirstspawn: true
  nerdspawn.spawn:
    description: Allow a player to teleport to spawn
    default: op
  nerdspawn.setspawn:
    description: Allow a player to set the spawn location
    default: op
  nerdspawn.setfirstspawn:
    description: Allow a player to set the initial spawn location
    default: op

